import json
from pathlib import Path
from collections import Counter


def save_json_report(findings, output_dir):
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    report_file = output_path / "report.json"

    data = [finding.to_dict() for finding in findings]

    with open(report_file, "w") as f:
        json.dump(data, f, indent=4)

    return report_file


def save_summary(findings, output_dir):
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    summary_file = output_path / "summary.txt"

    severity_counter = Counter(
        finding.severity.upper() for finding in findings
    )

    total = len(findings)

    lines = [
        "AppSec Toolkit Scan Summary",
        "=" * 32,
        f"Total findings: {total}",
        "",
        "Severity breakdown:",
    ]

    for severity, count in severity_counter.items():
        lines.append(f"- {severity}: {count}")

    lines.append("")
    lines.append("Generated by AppSec Toolkit v8")

    with open(summary_file, "w") as f:
        f.write("\n".join(lines))

    return summary_file